# Generated by Django 4.0.2 on 2022-02-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_nomi_uz', models.CharField(max_length=50)),
                ('fan_nomi_ru', models.CharField(max_length=50)),
                ('hafta_kuni', models.SmallIntegerField()),
                ('soat', models.TimeField()),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.sinf')),
            ],
        ),
    ]
